# Generated by Django 4.0.5 on 2022-06-29 15:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=200)),
                ('solved_status', models.CharField(max_length=200)),
                ('score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appoj.problems', verbose_name='problem_id')),
                ('input', models.CharField(max_length=200)),
                ('output', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoj.problems', verbose_name='problem_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoj.userprofile', verbose_name='user.id')),
            ],
        ),
    ]
