# Generated by Django 4.0.5 on 2022-07-01 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appoj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='solved_status',
        ),
        migrations.CreateModel(
            name='Verdicts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_status', models.CharField(max_length=200)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoj.problems', verbose_name='problem_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoj.userprofile', verbose_name='verdict_user_id')),
            ],
        ),
    ]
